#!/bin/bash
#SBATCH --partition=mque_r6
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --mem-per-cpu=8000
#SBATCH -J DIIID-64A
#SBATCH --time=02:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=jardin@pppl.gov



cp /p/tsc/FiniteElement/SGI/temporary_directory/trunk/unstructured/_sunfire.pppl.gov-opt-25/m3dc1_2d .
mpiexec --report-bindings --bind-to none -np 8 ./m3dc1_2d -pc_factor_mat_solver_package mumps
