MPIVER=intel2019u3-openmpi4.0.3
PETSCVER=petsc3.13.5
PETSC_VER=petsc-3.13.5
CMAKETYPE=Release
PETSC_DIR=/p/tsc/m3dc1/lib/SCORECLib/PETSC/$PETSC_VER
PETSC_ARCH=real-rhel7-$MPIVER-slmaster
PARMETIS_INSTALL_DIR=$PETSC_DIR/$PETSC_ARCH
ZOLTAN_INSTALL_DIR=$PETSC_DIR/$PETSC_ARCH
PREFIX=/p/tsc/m3dc1/lib/SCORECLib/rhel7/$MPIVER/$PETSCVER/adapt
#module load intel/2019.u3 openmpi/4.0.3
#cp M3DC1/m3dc1_scorec/config-files/test-CMakeLists.txt ./test/CMakeLists.txt
#cp M3DC1/m3dc1_scorec/test/create_smb/*cc ./test
cmake .. \
  -DCMAKE_C_COMPILER="mpicc" \
  -DCMAKE_CXX_COMPILER="mpicxx" \
  -DCMAKE_C_FLAGS=" -g -O2 -Wall -Wextra" \
  -DCMAKE_CXX_FLAGS=" -g -O2 -Wall -Wextra" \
  -DSCOREC_ENABLE_CXX11=ON\
  -DZOLTAN_INCLUDE_DIR="$ZOLTAN_INSTALL_DIR/include" \
  -DZOLTAN_LIBRARY="$ZOLTAN_INSTALL_DIR/lib/libzoltan.a" \
  -DPARMETIS_INCLUDE_DIR="$PARMETIS_INSTALL_DIR/include" \
  -DPARMETIS_LIBRARY="$PARMETIS_INSTALL_DIR/lib/libparmetis.a" \
  -DMETIS_INCLUDE_DIR="$PARMETIS_INSTALL_DIR/include" \
  -DMETIS_LIBRARY="$PARMETIS_INSTALL_DIR/lib/libmetis.a" \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  -DIS_TESTING=OFF \
  -DENABLE_ZOLTAN=ON \
  -DBUILD_EXES=ON \
  -DCMAKE_BUILD_TYPE=$CMAKETYPE
