HOST=cori
MPIVER=mpich7.7.6
ARCH=hsw
CMAKETYPE=Release
PETSC_VER=petsc-3.9.3
PETSCVER=petsc3.9.3
#PETSC_DIR=/global/project/projectdirs/mp288/cori/petsc/$PETSC_VER
#PETSC_ARCH=real-intel-$MPIVER-$ARCH
PETSC_DIR=/global/homes/j/jinchen/project/PETSC/$PETSC_VER
PETSC_ARCH=cori-hsw-mpich776-real-nomkl-510
#load module cray-hdf5-parallel
PARMETIS_DIR=$PETSC_DIR/$PETSC_ARCH
ZOLTAN_DIR=/global/project/projectdirs/mp288/cori/scorec/$MPIVER/$ARCH-$PETSCVER
PUMI_DIR=$ZOLTAN_DIR
PREFIX=$ZOLTAN_DIR/adapt
cmake .. \
  -DCMAKE_C_COMPILER="cc" \
  -DCMAKE_CXX_COMPILER="CC" \
  -DCMAKE_Fortran_COMPILER="ftn" \
  -DCMAKE_C_FLAGS=" -g -O2 -DPETSCMASTER -I$PETSC_DIR/include" \
  -DCMAKE_CXX_FLAGS=" -g -O2 -DPETSCMASTER -I$PETSC_DIR/include" \
  -DCMAKE_Fortran_FLAGS="-fpic -g -O2" \
  -DZOLTAN_LIBRARY="$ZOLTAN_DIR/lib/libzoltan.a" \
  -DPARMETIS_LIBRARY="$PARMETIS_DIR/lib/libparmetis.a" \
  -DMETIS_LIBRARY="$PARMETIS_DIR/lib/libmetis.a" \
  -DSCOREC_INCLUDE_DIR="$PUMI_DIR/include" \
  -DSCOREC_LIB_DIR="$PUMI_DIR/lib" \
  -DPETSC_INCLUDE_DIR="$PETSC_DIR/$PETSC_ARCH/include" \
  -DPETSC_LIB_DIR="$PETSC_DIR/$PETSC_ARCH/lib" \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" \
  -DENABLE_TESTING=OFF \
  -DENABLE_COMPLEX=OFF \
  -DCMAKE_BUILD_TYPE=$CMAKETYPE
