HOST=cori
MPIVER=mvapich2.3.2
PETSCVER=petsc3.12.4
PETSC_VER=petsc-3.12.4
#esslurm          2) jdk/1.8.0_202    3) cuda/10.2.89     4) pgi/19.10        5) mvapich2/2.3.2
ARCH=cuda10.2-pgi19.10
CMAKETYPE=Release
PETSC_DIR=/project/projectdirs/mp288/jinchen/PETSC/petsc
PETSC_ARCH=corigpu-pgi1910-mvapich2.232-master-real
PARMETIS_DIR=$PETSC_DIR/$PETSC_ARCH
SCOREC_DIR=/global/project/projectdirs/mp288/$HOST/scorec/$MPIVER/$ARCH-$PETSCVER
ZOLTAN_DIR=$SCOREC_DIR
PUMI_DIR=$SCOREC_DIR #enter your PUMI install dir
PREFIX=$SCOREC_DIR #enter your M3DC1_SCOREC install dir
cmake .. \
  -DCMAKE_C_COMPILER="mpicc" \
  -DCMAKE_CXX_COMPILER="mpicxx" \
  -DCMAKE_Fortran_COMPILER="mpif90" \
  -DCMAKE_C_FLAGS="-DPETSCMASTER -I$PETSC_DIR/include" \
  -DCMAKE_CXX_FLAGS="-DPETSCMASTER -I$PETSC_DIR/include" \
  -DCMAKE_Fortran_FLAGS="-fpic" \
  -DZOLTAN_LIBRARY="$ZOLTAN_DIR/lib/libzoltan.a" \
  -DPARMETIS_LIBRARY="$PARMETIS_DIR/lib/libparmetis.a" \
  -DMETIS_LIBRARY="$PARMETIS_DIR/lib/libmetis.a" \
  -DSCOREC_INCLUDE_DIR="$PUMI_DIR/include" \
  -DSCOREC_LIB_DIR="$PUMI_DIR/lib" \
  -DPETSC_INCLUDE_DIR="$PETSC_DIR/$PETSC_ARCH/include" \
  -DPETSC_LIB_DIR="$PETSC_DIR/$PETSC_ARCH/lib" \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" \
  -DENABLE_TESTING=OFF \
  -DENABLE_COMPLEX=OFF \
  -DCMAKE_BUILD_TYPE=$CMAKETYPE
