MPIVER=mvapich2.232
PETSCVER=petsc
PETSC_VER=petsc
ARCH=cuda102-pgi1910
CMAKETYPE=Release
PETSC_DIR=/project/projectdirs/mp288/jinchen/PETSC/petsc
PETSC_ARCH=corigpu-pgi1910-mvapich2.232-cuda10289-master-real2-zoltan
PARMETIS_DIR=$PETSC_DIR/$PETSC_ARCH
SCOREC_DIR=$PETSC_DIR/$PETSC_ARCH
ZOLTAN_DIR=$SCOREC_DIR
PUMI_DIR=$PETSC_DIR/$PETSC_ARCH #enter your PUMI install dir
PREFIX=$PETSC_DIR/$PETSC_ARCH #enter your M3DC1_SCOREC install dir
#esslurm          2) jdk/1.8.0_202    3) cuda/10.2.89     4) pgi/19.10        5) mvapich2/2.3.2

cmake .. \
  -DCMAKE_C_COMPILER="mpicc" \
  -DCMAKE_CXX_COMPILER="mpicxx" \
  -DCMAKE_Fortran_COMPILER="mpif90" \
  -DCMAKE_C_FLAGS="-DPETSCMASTER -I$PETSC_DIR/include" \
  -DCMAKE_CXX_FLAGS="-DPETSCMASTER -I$PETSC_DIR/include" \
  -DCMAKE_Fortran_FLAGS="-fpic" \
  -DZOLTAN_LIBRARY="$ZOLTAN_DIR/lib/libzoltan.a" \
  -DPARMETIS_LIBRARY="$PARMETIS_DIR/lib/libparmetis.a" \
  -DMETIS_LIBRARY="$PARMETIS_DIR/lib/libmetis.a" \
  -DSCOREC_INCLUDE_DIR="$PUMI_DIR/include" \
  -DSCOREC_LIB_DIR="$PUMI_DIR/lib" \
  -DPETSC_INCLUDE_DIR="$PETSC_DIR/$PETSC_ARCH/include" \
  -DPETSC_LIB_DIR="$PETSC_DIR/$PETSC_ARCH/lib" \
  -DHDF5_INCLUDE_DIR="$HDF5_DIR/include" \
  -DHDF5_LIB_DIR="$HDF5_DIR/lib" \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" \
  -DENABLE_TESTING=OFF \
  -DENABLE_COMPLEX=ON \
  -DCMAKE_BUILD_TYPE=$CMAKETYPE
