PETSC_DIR=/lore/seol/petsc-3.7.6
PETSC_ARCH=real-openmpi
PARMETIS_DIR=$PETSC_DIR/$PETSC_ARCH
ZOLTAN_DIR=/lore/seol/openmpi-petsc3.7.6-install
PREFIX=/lore/seol/openmpi-petsc3.7.6-sim-install
cmake .. \
  -DCMAKE_C_COMPILER="/usr/local/openmpi/latest/bin/mpicc" \
  -DCMAKE_CXX_COMPILER="/usr/local/openmpi/latest/bin/mpicxx" \
  -DCMAKE_C_FLAGS=" -g -O2 -DNDEBUG -Wall -Wextra -Werror" \
  -DCMAKE_CXX_FLAGS=" -g -O2 -DNDEBUG  -Wall -Wextra -Werror" \
  -DENABLE_ZOLTAN=ON \
  -DZOLTAN_INCLUDE_DIR="$ZOLTAN_DIR/include" \
  -DZOLTAN_LIBRARY="$ZOLTAN_DIR/lib/libzoltan.a" \
  -DMETIS_INCLUDE_DIR="$PARMETIS_DIR/include" \
  -DPARMETIS_INCLUDE_DIR="$PARMETIS_DIR/include" \
  -DPARMETIS_LIBRARY="$PARMETIS_DIR/lib/libparmetis.a" \
  -DMETIS_LIBRARY="$PARMETIS_DIR/lib/libmetis.a" \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  -DSCOREC_CXX_WARNINGS=OFF \
  -DBUILD_EXES=OFF \
  -DIS_TESTING=OFF \
  -DMESHES=/lore/seol/develop/meshes \
  -DMPIRUN=/usr/local/openmpi/latest/bin/mpirun \
  -DCMAKE_BUILD_TYPE=Debug \
  -DENABLE_SIMMETRIX=ON \
  -DSIM_MPI=openmpi165-ib \
  -DSIMMETRIX_INCLUDE_DIR=/net/common/meshSim/11.0-170826/include \
  -DSIMMETRIX_LIB_DIR=/net/common/meshSim//11.0-170826/lib/x64_rhel6_gcc44

