MPIVER=nvidia8.3.3-mpich8.1.22
CMAKETYPE=Release
PETSC_VER=petsc-3.18.4
PETSCVER=petsc3.18.4
PETSC_DIR=/global/cfs/cdirs/mp288/scorec-pmt/petsc/$PETSC_VER
PETSC_ARCH=real-$MPIVER
PARMETIS_DIR=$PETSC_DIR/$PETSC_ARCH
METIS_DIR=$PETSC_DIR/$PETSC_ARCH
ZOLTAN_DIR=$PETSC_DIR/$PETSC_ARCH
PREFIX=/global/cfs/cdirs/mp288/scorec-pmt/$MPIVER/$PETSCVER
#module load cmake python/3.9-anaconda-2021.11 PrgEnv-nvidia/8.3.3 fast-mkl-amd gsl
cmake .. \
  -DCMAKE_C_COMPILER="cc" \
  -DCMAKE_CXX_COMPILER="CC" \
  -DSCOREC_CXX_WARNINGS=OFF \
  -DSCOREC_CXX_OPTIMIZE=OFF \
  -DENABLE_ZOLTAN=ON \
  -DBUILD_EXES=ON \
  -DIS_TESTING=OFF \
  -DZOLTAN_INCLUDE_DIR="$ZOLTAN_DIR/include" \
  -DZOLTAN_LIBRARY="$ZOLTAN_DIR/lib/libzoltan.a" \
  -DPARMETIS_INCLUDE_DIR="$PARMETIS_DIR/include" \
  -DPARMETIS_LIBRARY="$PARMETIS_DIR/lib/libparmetis.a" \
  -DMETIS_INCLUDE_DIR="$METIS_DIR/include" \
  -DMETIS_LIBRARY="$METIS_DIR/lib/libmetis.a" \
  -DBUILD_EXES=ON \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" \
  -DCMAKE_BUILD_TYPE=$CMAKETYPE
