#MPIVER=intel2021-intelmpi2021
CMAKETYPE=Release
PETSC_DIR=/global/cfs/cdirs/mp288/jinchen/PETSC/petsc.20210927
PETSC_ARCH=nvidia-hpc-sdk-6-cplx
PARMETIS_DIR=$PETSC_DIR/$PETSC_ARCH
SCOREC_DIR=$PETSC_DIR/$PETSC_ARCH
PREFIX=$PETSC_DIR/$PETSC_ARCH
#add -DPETSCMASTER for petsc 3.8.3 or higher

cmake .. \
  -DCMAKE_C_COMPILER=cc \
  -DCMAKE_CXX_COMPILER=CC \
  -DCMAKE_Fortran_COMPILER=ftn \
  -DCMAKE_C_FLAGS=" -g -fPIC -O0 -DPETSCMASTER -DOLDMA -I$PETSC_DIR/include -I/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/cuda/11.4/include/" \
  -DCMAKE_CXX_FLAGS=" -g -fPIC -O0 -DPETSCMASTER -DOLDMA -I$PETSC_DIR/include -I/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/cuda/11.4/include/" \
  -DCMAKE_Fortran_FLAGS="-fPIC "\
  -DPARMETIS_LIBRARY="$PARMETIS_DIR/lib/libparmetis.a" \
  -DMETIS_LIBRARY="$PARMETIS_DIR/lib/libmetis.a" \
  -DSCOREC_INCLUDE_DIR="$SCOREC_DIR/include" \
  -DSCOREC_LIB_DIR="$SCOREC_DIR/lib" \
  -DPETSC_INCLUDE_DIR="$PETSC_DIR/$PETSC_ARCH/include" \
  -DPETSC_LIB_DIR="$PETSC_DIR/$PETSC_ARCH/lib" \
  -DENABLE_TESTING=OFF \
  -DENABLE_COMPLEX=ON \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" \
  -DCMAKE_BUILD_TYPE=$CMAKETYPE \

