HOST=perseus
CMAKETYPE=Release
MPIVER=intel18.0-mpi2018.3
PETSC_VER=petsc-3.12.4
PETSCVER=petsc3.12.4
PETSC_DIR=/home/jinchen/LIB/petsc
PETSC_ARCH=real-intelmpi
PARMETIS_DIR=$PETSC_DIR/$PETSC_ARCH
BUILD_ROOT=/projects/M3DC1/scorec/$MPIVER/$PETSCVER
ZOLTAN_DIR=$BUILD_ROOT
PREFIX=$BUILD_ROOT
#add -DPETSCMASTER for petsc 3.8.3 or higher
#module load intel/18.0/64/18.0.3.222  intel-mpi/intel/2018.3/64
cmake3 .. \
  -DCMAKE_C_COMPILER="mpicc" \
  -DCMAKE_CXX_COMPILER="mpicxx" \
  -DCMAKE_Fortran_COMPILER="mpif90" \
  -DCMAKE_C_FLAGS="-g -O0 -DPETSCMASTER -I$PETSC_DIR/include" \
  -DCMAKE_CXX_FLAGS="-g -O0 -DPETSCMASTER -I$PETSC_DIR/include" \
  -DCMAKE_Fortran_FLAGS="-fpic" \
  -DZOLTAN_LIBRARY="$ZOLTAN_DIR/lib/libzoltan.a" \
  -DPARMETIS_LIBRARY="$PARMETIS_DIR/lib/libparmetis.a" \
  -DMETIS_LIBRARY="$PARMETIS_DIR/lib/libmetis.a" \
  -DSCOREC_INCLUDE_DIR="$BUILD_ROOT/include" \
  -DSCOREC_LIB_DIR="$BUILD_ROOT/lib" \
  -DPETSC_INCLUDE_DIR="$PETSC_DIR/$PETSC_ARCH/include" \
  -DPETSC_LIB_DIR="$PETSC_DIR/$PETSC_ARCH/lib" \
  -DENABLE_TESTING=OFF \
  -DENABLE_COMPLEX=OFF \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" \
  -DCMAKE_BUILD_TYPE=$CMAKETYPE
