MPIVER=intel2019u3-openmpi4.0.3
PETSCVER=petsc3.13.5
PETSC_VER=petsc-3.13.5
CMAKETYPE=Release
PETSC_DIR=/p/tsc/m3dc1/lib/SCORECLib/PETSC/$PETSC_VER
PETSC_ARCH=real-rhel6-intel2019u3-openmpi4.0.3
PARMETIS_DIR=$PETSC_DIR/$PETSC_ARCH
ZOLTAN_DIR=$PETSC_DIR/$PETSC_ARCH
SCOREC_DIR=/p/tsc/m3dc1/lib/SCORECLib/rhel6/$MPIVER/$PETSCVER
PREFIX=$SCOREC_DIR
#module load intel/2019.u3 openmpi/4.0.1 gsl szip scalapack
cmake .. \
  -DCMAKE_C_COMPILER=mpicc \
  -DCMAKE_CXX_COMPILER=mpicxx \
  -DENABLE_ZOLTAN=ON \
  -DZOLTAN_INCLUDE_DIR="$ZOLTAN_DIR/include" \
  -DZOLTAN_LIBRARY="$ZOLTAN_DIR/lib/libzoltan.a" \
  -DPARMETIS_INCLUDE_DIR="$PARMETIS_DIR/include" \
  -DPARMETIS_LIBRARY="$PARMETIS_DIR/lib/libparmetis.a" \
  -DMETIS_INCLUDE_DIR="$PARMETIS_DIR/include" \
  -DMETIS_LIBRARY="$PARMETIS_DIR/lib/libmetis.a" \
  -DSCOREC_CXX_WARNINGS=OFF \
  -DSCOREC_CXX_OPTIMIZE=OFF \
  -DBUILD_EXES=ON \
  -DIS_TESTING=OFF \
  -DCMAKE_BUILD_TYPE=$CMAKETYPE \
  -DCMAKE_INSTALL_PREFIX=$PREFIX
