PETSC_DIR=/lore/seol/petsc-3.13.5
PETSC_ARCH=real-gcc4.8.5-v5m6xwi-mpich3.2.1-geowaxe
PARMETIS_INSTALL_DIR=$PETSC_DIR/$PETSC_ARCH
ZOLTAN_INSTALL_DIR=$PETSC_DIR/$PETSC_ARCH
PREFIX=/lore/seol/rhel7-gcc4.8.5-v5m6xwi-mpich3.2.1-geowaxe
#module load gcc/4.8.5-v5m6xwi mpich/3.2.1-geowaxe cmake
#module unload zlib/1.2.11-vhzh5cf
cmake .. \
  -DCMAKE_C_COMPILER=mpicc \
  -DCMAKE_CXX_COMPILER=mpicxx \
  -DCMAKE_C_FLAGS=" -g -O0" \
  -DCMAKE_CXX_FLAGS=" -g -O0" \
  -DENABLE_ZOLTAN=ON \
  -DZOLTAN_INCLUDE_DIR="$ZOLTAN_INSTALL_DIR/include" \
  -DZOLTAN_LIBRARY="$ZOLTAN_INSTALL_DIR/lib/libzoltan.a" \
  -DMETIS_INCLUDE_DIR="$PARMETIS_INSTALL_DIR/include" \
  -DMETIS_LIBRARY="$PARMETIS_INSTALL_DIR/lib/libmetis.a" \
  -DPARMETIS_INCLUDE_DIR="$PARMETIS_INSTALL_DIR/include" \
  -DPARMETIS_LIBRARY="$PARMETIS_INSTALL_DIR/lib/libparmetis.a" \
  -DENABLE_SIMMETRIX=OFF \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  -DSCOREC_CXX_WARNINGS=OFF \
  -DSCOREC_CXX_OPTIMIZE=OFF \
  -DUSE_XSDK_DEFAULTS=OFF \
  -DSCOREC_ENABLE_CXX11=ON \
  -DBUILD_EXES=ON \
  -DIS_TESTING=OFF \
  -DCMAKE_BUILD_TYPE=Debug
