HOST=stellar
CMAKETYPE=Release
MPIVER=intel2021.1.2-intelmpi2021.3.1
PETSC_VER=petsc-3.13.5
PETSCVER=petsc3.13.5
PETSC_DIR=/projects/M3DC1/PETSC/$PETSC_VER
PETSC_ARCH=real-$MPIVER
PARMETIS_DIR=$PETSC_DIR/$PETSC_ARCH
BUILD_ROOT=/projects/M3DC1/scorec/$HOST/$MPIVER/$PETSCVER
ZOLTAN_DIR=$PETSC_DIR/$PETSC_ARCH
PREFIX=$BUILD_ROOT
#add -DPETSCMASTER for petsc 3.8.3 or higher
# module load cmake/3.19.7 intel/2021.1.2 intel-mpi/intel/2021.3.1
cmake3 .. \
  -DCMAKE_C_COMPILER="mpiicc" \
  -DCMAKE_CXX_COMPILER="mpiicpc" \
  -DENABLE_ZOLTAN=ON \
  -DZOLTAN_INCLUDE_DIR="$ZOLTAN_DIR/include" \
  -DZOLTAN_LIBRARY="$ZOLTAN_DIR/lib/libzoltan.a" \
  -DMETIS_INCLUDE_DIR="$PARMETIS_DIR/include" \
  -DMETIS_LIBRARY="$PARMETIS_DIR/lib/libmetis.a" \
  -DPARMETIS_INCLUDE_DIR="$PARMETIS_DIR/include" \
  -DPARMETIS_LIBRARY="$PARMETIS_DIR/lib/libparmetis.a" \
  -DSCOREC_CXX_WARNINGS=ON \
  -DSCOREC_CXX_OPTIMIZE=OFF \
  -DUSE_XSDK_DEFAULTS=OFF \
  -DSCOREC_ENABLE_CXX11=ON \
  -DBUILD_EXES=ON \
  -DIS_TESTING=OFF \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  -DCMAKE_BUILD_TYPE=$CMAKETYPE
