HOST=stellar
CMAKETYPE=Release
MPIVER=intel2021.1.2-openmpi4.1.0
PETSC_VER=petsc-3.15.5
PETSCVER=petsc3.15.5
PETSC_DIR=/projects/M3DC1/PETSC/$PETSC_VER
PETSC_ARCH=real-$MPIVER
PARMETIS_DIR=$PETSC_DIR/$PETSC_ARCH
ZOLTAN_DIR=$PETSC_DIR/$PETSC_ARCH
BUILD_ROOT=/projects/M3DC1/scorec/$MPIVER/$PETSCVER
PREFIX=$BUILD_ROOT
#add -DPETSCMASTER for petsc 3.8.3 or higher
# module load intel/2021.1.2 openmpi/intel-2021.1/4.1.0
cmake .. \
  -DCMAKE_C_COMPILER=/usr/local/openmpi/4.1.0/intel20211/bin/mpicc \
  -DCMAKE_CXX_COMPILER=/usr/local/openmpi/4.1.0/intel20211/bin/mpicxx \
  -DCMAKE_Fortran_COMPILER=/usr/local/openmpi/4.1.0/intel20211/bin/mpif90 \
  -DCMAKE_C_FLAGS="-g -O0 -DOLDMA -DPETSCMASTER -I$PETSC_DIR/include" \
  -DCMAKE_CXX_FLAGS="-g -O0 -DOLDMA -DPETSCMASTER -I$PETSC_DIR/include" \
  -DCMAKE_Fortran_FLAGS="-fpic" \
  -DZOLTAN_LIBRARY="$ZOLTAN_DIR/lib/libzoltan.a" \
  -DPARMETIS_LIBRARY="$PARMETIS_DIR/lib/libparmetis.a" \
  -DMETIS_LIBRARY="$PARMETIS_DIR/lib/libmetis.a" \
  -DSCOREC_INCLUDE_DIR="$BUILD_ROOT/include" \
  -DSCOREC_LIB_DIR="$BUILD_ROOT/lib" \
  -DPETSC_INCLUDE_DIR="$PETSC_DIR/$PETSC_ARCH/include" \
  -DPETSC_LIB_DIR="$PETSC_DIR/$PETSC_ARCH/lib" \
  -DENABLE_TESTING=OFF \
  -DENABLE_COMPLEX=OFF \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" \
  -DCMAKE_BUILD_TYPE=$CMAKETYPE
