HOST=traverse
MPIVER=nvhpc22.5-openmpi4.1.4-cuda11.7
CMAKETYPE=Release
PETSC_VER=petsc-3.18.2
PETSCVER=petsc3.18.2
PETSC_DIR=/projects/M3DC1/scorec/petsc/$PETSC_VER
PETSC_ARCH=real-$MPIVER
PARMETIS_DIR=$PETSC_DIR/$PETSC_ARCH
ZOLTAN_DIR=/projects/M3DC1/scorec/$HOST/$MPIVER/$PETSCVER
SCOREC_DIR=/projects/M3DC1/scorec/$HOST/$MPIVER/$PETSCVER
PREFIX=$SCOREC_DIR
#module load nvhpc/22.5  openmpi/cuda-11.7/nvhpc-22.5/4.1.4/64   
#module load hdf5/nvhpc-22.5/openmpi-4.1.3/1.10.6 gsl/1.15
#add -DPETSCMASTER for petsc 3.8.3 or higher
cmake .. \
  -DCMAKE_C_COMPILER=mpicc \
  -DCMAKE_CXX_COMPILER=mpicxx \
  -DCMAKE_Fortran_COMPILER=mpif90 \
  -DCMAKE_C_FLAGS=" -g -O0 -DOLDMA -DPETSCMASTER -I$PETSC_DIR/include" \
  -DCMAKE_CXX_FLAGS=" -g -O0 -DOLDMA -DPETSCMASTER -I$PETSC_DIR/include" \
  -DCMAKE_Fortran_FLAGS="-fpic "\
  -DSCOREC_INCLUDE_DIR="$SCOREC_DIR/include" \
  -DSCOREC_LIB_DIR="$SCOREC_DIR/lib" \
  -DENABLE_ZOLTAN=ON \
  -DZOLTAN_LIBRARY="$ZOLTAN_DIR/lib/libzoltan.a" \
  -DPARMETIS_LIBRARY="$PARMETIS_DIR/lib/libparmetis.a" \
  -DMETIS_LIBRARY="$PARMETIS_DIR/lib/libmetis.a" \
  -DPETSC_INCLUDE_DIR="$PETSC_DIR/$PETSC_ARCH/include" \
  -DPETSC_LIB_DIR="$PETSC_DIR/$PETSC_ARCH/lib" \
  -DENABLE_PETSC=ON \
  -DENABLE_COMPLEX=OFF \
  -DENABLE_TESTING=OFF \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  -DCMAKE_BUILD_TYPE=$CMAKETYPE
