MPIVER=nvhpc20.7-cuda11.0-openmpi4.0.4
CMAKETYPE=Release
PETSC_VER=petsc-3.13.5
PETSCVER=petsc3.13.5
PETSC_DIR=/projects/M3DC1/PETSC/$PETSC_VER
PETSC_ARCH=real-$MPIVER
PARMETIS_DIR=$PETSC_DIR/$PETSC_ARCH
ZOLTAN_DIR=/projects/M3DC1/scorec/$MPIVER/$PETSCVER
SCOREC_DIR=/projects/M3DC1/scorec/$MPIVER/$PETSCVER
PREFIX=/projects/M3DC1/scorec/$MPIVER/$PETSCVER
# module load nvhpc/20.7 openmpi/cuda-11.0/nvhpc-20.7/4.0.4/64 cudatoolkit/11.0 
#add -DPETSCMASTER for petsc 3.8.3 or higher
cmake3 .. \
  -DCMAKE_C_COMPILER=mpicc \
  -DCMAKE_CXX_COMPILER=mpicxx \
  -DCMAKE_Fortran_COMPILER=mpif90 \
  -DCMAKE_C_FLAGS=" -g -O0 -DOLDMA -DPETSCMASTER -I$PETSC_DIR/include" \
  -DCMAKE_CXX_FLAGS=" -g -O0 -DOLDMA -DPETSCMASTER -I$PETSC_DIR/include" \
  -DCMAKE_Fortran_FLAGS="-fpic "\
  -DSCOREC_INCLUDE_DIR="$SCOREC_DIR/include" \
  -DSCOREC_LIB_DIR="$SCOREC_DIR/lib" \
  -DENABLE_ZOLTAN=ON \
  -DZOLTAN_LIBRARY="$ZOLTAN_DIR/lib/libzoltan.a" \
  -DPARMETIS_LIBRARY="$PARMETIS_DIR/lib/libparmetis.a" \
  -DMETIS_LIBRARY="$PARMETIS_DIR/lib/libmetis.a" \
  -DPETSC_INCLUDE_DIR="$PETSC_DIR/$PETSC_ARCH/include" \
  -DPETSC_LIB_DIR="$PETSC_DIR/$PETSC_ARCH/lib" \
  -DENABLE_PETSC=ON \
  -DENABLE_COMPLEX=OFF \
  -DENABLE_TESTING=OFF \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  -DCMAKE_BUILD_TYPE=$CMAKETYPE
