#! /bin/sh
set -v
for file in C1restarto*
do
echo $file

newfile=`echo $file | cut -c-9`
newnum=`echo $file | cut -c11-`


echo $newfile
echo $newnum

mv $file $newfile$newnum

echo 

done
