#!/bin/bash
#SBATCH --partition=mque_r6
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --mem-per-cpu=8000
#SBATCH -J FRS
#SBATCH --time=12:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=jardin@pppl.gov

cp /p/tsc/FiniteElement/SGI/temporary_directory/trunk/unstructured/_sunfire.pppl.gov-complex-opt-25/m3dc1_2d_complex .

mpiexec --report-bindings --bind-to none -np 16 ./m3dc1_2d_complex

echo -n " Ended program at : ";date

