c
      common / arys2 /
     $     cpwtr(nths,nfm), cpwti(nths,nfm),
     $     cwptr(nths,nfm), cwpti(nths,nfm),
     $     bxpwr(nths,nfm),bxpwi(nths,nfm),
     $     bzpwr(nths,nfm),bzpwi(nths,nfm),
     $     bnpwr(nths,nfm),bnpwi(nths,nfm),
     $     bnwpr(nths,nfm),bnwpi(nths,nfm),
     $     bnpptr(nths),bnppti(nths),
     $     bnpwtr(nths),bnpwti(nths),
     $     bnwptr(nths),bnwpti(nths)
