PETSC_DIR=/lore/seol/petsc-3.5.4
PETSC_ARCH=real-openmpi1.6.5
PARMETIS_DIR=$PETSC_DIR/$PETSC_ARCH
ZOLTAN_DIR=/lore/seol/openmpi-gcc4.4.5-install
SIM_ARCHOS=x64_rhel6_gcc44
SIM_VER=14.0-190513dev
PREFIX=/lore/seol/openmpi-gcc4.4.5-$SIM_VER-install
cmake .. \
  -DCMAKE_C_COMPILER="/usr/local/openmpi/latest/bin/mpicc" \
  -DCMAKE_CXX_COMPILER="/usr/local/openmpi/latest/bin/mpicxx" \
  -DENABLE_ZOLTAN=ON \
  -DZOLTAN_INCLUDE_DIR="$ZOLTAN_DIR/include" \
  -DZOLTAN_LIBRARY="$ZOLTAN_DIR/lib/libzoltan.a" \
  -DPARMETIS_INCLUDE_DIR="$PARMETIS_DIR/include" \
  -DPARMETIS_LIBRARY="$PARMETIS_DIR/lib/libparmetis.a" \
  -DMETIS_INCLUDE_DIR="$PARMETIS_DIR/include" \
  -DMETIS_LIBRARY="$PARMETIS_DIR/lib/libmetis.a" \
  -DCMAKE_BUILD_TYPE=Debug \
  -DENABLE_SIMMETRIX=ON \
  -DSIMMETRIX_INCLUDE_DIR=/net/common/meshSim/$SIM_VER/include \
  -DSIMMETRIX_LIB_DIR=/net/common/meshSim/$SIM_VER/lib/$SIM_ARCHOS \
  -DSIM_MPI=openmpi165-ib \
  -DBUILD_EXES=OFF \
  -DCMAKE_INSTALL_PREFIX="$PREFIX"
